# vim:ft=ansible
---

- command: docker rm -f mongo-express
  ignore_errors: True

- name: Run express
  docker:
    name: mongo-express
    image: mongo-express
    state: started
    net: host
    env:
      ME_CONFIG_OPTIONS_EDITORTHEME: monokai
      ME_CONFIG_MONGODB_SERVER: "{{ ansible_eth1.ipv4.address }}"
      ME_CONFIG_MONGODB_ADMINUSERNAME: siteRootAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: "{{ mongo_root_password }}"
    ports:
    - "8081:8081"
  when: is_master|default("no") == "yes"
